---
title: "Cálculo diferencial e integral"
subtitle: "⚔"
author: "Tonalli Rodríguez López"
institute: "Vocare"
date: "2021/04/12"
output:
  xaringan::moon_reader:
    lib_dir: libs
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
---
class: inverse, center, middle

# Límites

---

# Definición

Escribimos

$$\lim_{x \to a} f(x) = L$$
y decimos "el límite de $f(x)$, cuándo $x$ se aproxima a $a$, es igual a $L$"

--

si podemos hacer los valores de $f(x)$ arbitrariamente cercanos a $L$ al tomar $x$ suficientemente cercana a $a$ (tanto por el lado izquierdo como por el lado derecho de $a$) __pero no igual a $a$__.

---

# Ejemplo

Sea

$$f(x) = \frac{x - 1}{x^2 - 1}$$
y

$$g(x) = 
\begin{cases} 
  f(x) & x \neq 1 \\
  2    & x =    1 
\end{cases}$$

Calcula el valor de 

-  $\lim\limits_{x \to 1} f(x)$
-  $\lim\limits_{x \to 1} g(x)$

.footnote[Observa que la función $f(x)$ no está definida cuando $x = 1$.]

---

# Teoremas sobre límites

Sean $\lim\limits_{x \to a} f(x) = L_1$ y $\lim\limits_{x \to a} g(x) = L_2$, entonces:

--

- $\lim\limits_{x \to a} c = c$, con $c$ constante

--

- $\lim\limits_{x \to a} x = a$

--

- $\lim\limits_{x \to a} c f(x) = c \cdot \lim\limits_{x \to a} f(x) = c \cdot L_1$

--

- $\lim\limits_{x \to a} [f(x) + g(x)] = \lim\limits_{x \to a} f(x) + \lim\limits_{x \to a} g(x) = L_1 + L_2$

--

- $\lim\limits_{x \to a} [f(x) \cdot g(x)] = \lim\limits_{x \to a} f(x) \cdot \lim\limits_{x \to a} g(x) = L_1  \cdot L_2$

--

- $\lim\limits_{x \to a} \frac{f(x)}{g(x)} = \frac{\lim\limits_{x \to a} f(x)}{\lim\limits_{x \to a} g(x)}=\frac{L_1}{L_2}$

--

- $\lim\limits_{x \to a} [f(x)]^{n} = [\lim\limits_{x \to a} f(x)]^{n}$

---

# Ejercicios

Obtener los siguientes límites:

- $\lim\limits_{x \to -1} \frac{3x-7}{2x+5}$

--

- Si $\lim\limits_{x \to -2} f(x) = 3$ y $\lim\limits_{x \to -2} g(x) = 4$.
  ¿Cuál es el valor de $\lim\limits_{x \to -2} \left[{f(x) + g(x)}\right]$?

--

- Si $\lim\limits_{x \to -10} \left[{3k f(x) -2k g(x)}\right] = -10$.
  ¿Cuál es el valor de $k$ si $\lim\limits_{x \to -10} f(x) = -10$ y 
  $\lim\limits_{x \to -10} g(x) = -10$?

---

# Formas indeterminadas

Al calcular un límite se puede presentar la forma indeterminada $\frac{0}{0}$, la cual se 
elimina mediante una simplificación al factorizar las expresiones dadas.

Obtener los siguientes límites:

- $\lim\limits_{x \to -4} \frac{x^2-x-20}{x^2-16}$

--

- $\lim\limits_{x \to -2} \frac{x+2}{x^2+5x+6}$

--

- $\lim\limits_{x \to 0} \frac{x^2-3x}{x}$

---

# Formas indeterminadas - parte 2

Si $F(x) = \frac{f(x)}{g(x)}$, los resultados de los límites para las formas $\lim\limits_{x \to a} F(x)$, $\lim\limits_{x \to \infty} F(x)$ y $\lim\limits_{x \to - \infty} F(x)$ son:

--

- Si se obtiene una expresión de la forma $\frac{L}{\infty}$, entonces, el límite es 0.

--

- Si se obtiene una expresión de la forma $\frac{\infty}{L}$, entonces, el límite es infinito.

--

- Si se obtiene una expresión de la forma $\frac{L}{0}$, entonces, el límite es infinito.

--

<br>
Obtener los siguientes límites:

- $\lim\limits_{x \to \infty} \frac{6x^3 - 5x^2 - 3x + 2}{4x^3 - 2x+6}$

--

- $\lim\limits_{x \to \infty} \frac{2x^2 - 6x + 7}{5x^3 + 2x - 3}$

--

- $\lim\limits_{x \to \infty} \frac{2x^2 + 3}{x + 1}$

---

# Formas indeterminadas - parte 2
## Teorema

Si $\lim\limits_{x \to \infty} \frac{a_{n} x^{n} + a_{n-1} x^{n-1} + a_{n-2} x^{n-2} + \ldots + a_0}{b_{m} x^{m} + b_{m-1} x^{m-1} + b_{m-2} x^{m-2} + \ldots + b_0}$, entonces:

--

- Si $n > m$, entonces el límite es **infinito**.

--

- Si $n < m$, entonces el límite es **cero**.

--

- Si $n = m$, entonces el límite es $\frac{a_n}{b_n}$

--

<br>
Cálcula los límites anteriores.

---
class: inverse, center, middle

# La derivada

---

# La recta tangente

<iframe src="https://www.geogebra.org/graphing/su6kyakb?embed" width="800" height="500" allowfullscreen style="border: 1px solid #e4e4e4;border-radius: 4px;" frameborder="0"></iframe>

???
Sea $P$ un punto en una curva y sea $Q$ un punto móvil cercano a $P$ en esa curva.
Considere la recta que pasa por $P$ y $Q$, llamada recta secante. La recta tangente
en $P$ es la posición límite (si ésta existe) de la recta secante cuando $Q$ se 
mueve hacia $P$ a lo largo de la curva

---

# Derivada

La derivada de una función $f$ es otra función $f'$ cuyo valor en cualquier número $x$ es

$$f'(x) = \lim_{\Delta x \to 0} \frac{f(x + \Delta x) - f(x)}{\Delta x}$$
Si este límite existe, decimos que $f$ es **derivable** en $x$.

--

Si $y = f(x)$, podemos denotar la derivada de $f$ por medio de

$$\begin{align}
f'(x) & & \mathrm{o} & & D_{x} f(x) & & \mathrm{o} & & \frac{dy}{dx}
\end{align}$$

???
Determinar una derivada recibe el nombre de derivación.

---

# Cálculo de derivadas
## Ejemplos

Determina la derivada de las siguientes funciones

- $f(x) = 4x+1$

- $f(x) = x^2 + 5 x$

- $f(x) = \frac{1}{x}$

---

# Derivadas de funciones algebraicas
## Reglas de derivación

.pull-left[
- $\frac{d}{dx}(c) = 0$

- $\frac{d}{dx}(x) = 1$

- $\frac{d}{dx}(cv)= c \frac{dv}{dx}$

- $\frac{d}{dx}(u \pm v) = \frac{du}{dx} \pm \frac{dv}{dx}$
]
.pull-right[
- $\frac{d}{dx}(v^n) = n v^{n-1} \frac{dv}{dx}$

- $\frac{d}{dx}(\sqrt{v}) = \frac{1}{2 \sqrt{v}} \frac{dv}{dx}$

- $\frac{d}{dx}(u \cdot v) = \frac{du}{dx} \cdot v + u \cdot \frac{dv}{dx}$

- $\frac{d}{dx}(\frac{u}{v}) = \frac{\frac{du}{dx} \cdot v - u \cdot \frac{dv}{dx}}{v^2}$
]

Donde $c$: constante; $x$, $u$, y $v$: variables.

???
El proceso de encontrar la derivada de una función a partir de la definición, puede ser
engorroso y tedioso. por lo que se presentan las siguientes reglas para determinar derivadas 
sin tener que usar la definición

---

# Cálculo de derivadas
## Ejemplos - Funciones algebraicas

Determina la derivada de las siguientes funciones:

.pull-left[
- $y = {x^2+8x-10}$

- $y=4x^{5/4}-3x^{4/3} + 8$

- $y=\left(2x-3\right) \left(x+5\right)$
]
.pull-right[
- $y=\frac{2x+3}{x-5}$

- $y=\sqrt[3]{5-6x}$

- $y=(5x-x^2)^3$
]

---

# Derivadas de funciones trigonométricas
## Reglas de derivación

.pull-left[
- $\frac{d}{dx} \sin{(v)} = \cos{(v)} \cdot \frac{dv}{dx}$

- $\frac{d}{dx} \cos{(v)} = - \sin{(v)} \cdot \frac{dv}{dx}$

- $\frac{d}{dx} \tan{(v)}= \sec^{2}{(v)} \cdot \frac{dv}{dx}$
]
.pull-right[
- $\frac{d}{dx} \cot{(v)} = -\csc^{2}{(v)} \frac{dv}{dx}$

- $\frac{d}{dx} \sec{(v)} = \sec{(v)} \cdot \tan{(v)} \cdot \frac{dv}{dx}$

- $\frac{d}{dx} \csc{(v)} = - \csc{(v)} \cdot \cot{(v)} \cdot \frac{dv}{dx}$
]

Donde $v$: variable.

???
Notas

---

# Cálculo de derivadas
## Ejemplos - Funciones trigonométricas

Determina la derivada de las siguientes funciones:

.pull-left[
- $y=\sin\left(1-3x^2\right)$

- $y=5 \sin 2x^3$
]
.pull-right[
- $y=\csc 3x^4$

- $y=\sec x^2$
]

---

# Derivadas de funciones exponenciales y logarítmicas
## Reglas de derivación

.pull-left[
- $\frac{d}{dx} e^{v} = e^{v} \cdot \frac{dv}{dx}$

- $\frac{d}{dx} a^{v} = \ln{a} \cdot a^{v} \cdot \frac{dv}{dx}$
]
.pull-right[
- $\frac{d}{dx} \ln{(v)} = \frac{1}{v} \cdot \frac{dv}{dx}$

- $\frac{d}{dx} \log_{a}{(v)} = \frac{1}{\ln{(a)} \cdot v} \cdot \frac{dv}{dx}$
]

donde $e$: base del logaritmo natural, $a$: constante, $v$: variable

---

# Cálculo de derivadas
## Ejemplos - exponenciales y logarítmicas

Determina la derivada de las siguientes funciones:

.pull-left[
- $y=e^{1-2x}$

- $y=x^2 + \cos{(x)} - e^x$

- $y = e^{\tan {(2x)}}$
]
.pull-right[
- $y = \frac{e^{x} + e^{-x}}{2}$

- $y = 3^{\sin{(x)}}$

- $y = 9 \ln \left(x^2 - 4\right)$
]

---

# Regla de la cadena

Sea la función $y = g(u)$ y $u = h(x)$, entonces la derivada $\frac{dy}{dx}$, se define como:

$$\frac{dy}{dx} = \frac{dy}{du} \cdot \frac{du}{dx}$$
--

Determina la derivada de las siguientes funciones:


- $y = 2u^3 - u^2$, $u = \sqrt{x}$

- $y = \sin(u^2 - 1)$, $u = \cos x$


---
class: center, middle
# ¡Gracias!

Diapositivas creadas a través del paquete R [**xaringan**](https://github.com/yihui/xaringan).
